### PR TITLE
Add version handling

### PR DESCRIPTION
**Pull request by rubene**
Give ability to grape-swagger to distinguish  and handle multiple grape api versions.

Repurposing api_version to pull desired version from query string.
Only routes for the specified version will be returned

Possible related issues:
[141](https://github.com/tim-vandecasteele/grape-swagger/issues/141)
[146](https://github.com/tim-vandecasteele/grape-swagger/issues/146)
[38](https://github.com/tim-vandecasteele/grape-swagger/issues/38)

### CODE REVIEW

**Comment by whatasunnyday** [comment]
@dblock What's blocking this from a merge? Tests?

**Comment by dblock** [comment]
Yes, tests + rebase.

**Comment by dm1try** [comment]
Does it work?

**Comment by bachetouane** [comment]
Hello, what's the status on this ?

**Comment by dblock** [comment]
There's code, no tests. Please finish this PR.

**Comment by rubene** [comment]
We are still looking into this, there is a javascript issue that have to be resolved for these changes to work. @MathieuGilbert @mvandenbeuken

**Comment by florrain** [comment]
Bump for this, it's been a while with no update. :facepunch:

**Comment by LeFnord** [comment]
please re-target against `swagger-1.2` branch or close

**Comment by mcfilib** [comment]
@rubene this is something that'd be great to have. was it ever picked up again in another pull request?

**Comment by mcfilib** [comment]
> We are still looking into this, there is a javascript issue that have to be resolved for these changes to work. @MathieuGilbert @mvandenbeuken

what was the javascript issue?

**Comment by zjullion** [comment]
@MathieuGilbert @mvandenbeuken @rubene I would also like to know wha the issues were, and if this will ever be merged.

**Pull request closed without merging**
