### PR TITLE
adds version matrix [skip ci]

### PR DESCRIPTION
**Pull request by LeFnord**

### CODE REVIEW

**Comment by LeFnord** [comment]
@dblock pleas could you have a look on it

**Comment by dblock** [comment]
Maybe should be called "Compatibility" and say something like "The following versions of grape, grape-entity and grape-swagger can currently be used together."?

**Comment by dblock** [comment]
Feel free to amend/merge.

**Comment by LeFnord** [comment]
@dblock but what version of grape-entity did 0.11.0 support?

**Comment by dblock** [comment]
Hmmm, I want to say "all" but I am not sure.

**Comment by dblock** [comment]
The Travis.yml on that tag might be helpful.

**Pull request merged**
