### PR TITLE
Fixes the regexp used for parsing routes

### PR DESCRIPTION
**Pull request by senhalil**
When called `add_swagger_documentation` raises the following warning which is due to vertical bars `|` since they are parsed as literal characters and not as OR's in a character set `[]` definition.

```
grape-swagger-1.4.2/lib/grape-swagger.rb:35: warning: character class has duplicated range: /\/([\p{Alnum}|\-|\_]*?)[\.\/\(]/
```

### CODE REVIEW

**Comment by senhalil** [comment]
It doesn't look like to me that the broken tests are due to my PR but I can fix them if that is the case. Let me know if that is the case please.

**Comment by senhalil** [comment]
I just rebased the PR. Can someone give me some feedback? Afaiac, the regexp definition is not correct and needs a fix.

**Comment by senhalil** [comment]
I just rebased the PR. Can someone give me some feedback -- maybe @LeFnord ?

**Comment by LeFnord** [comment]
thanks @senhalil … makes sense to me

**Pull request merged**
