### PR TITLE
Require Grape 0.16.2 and fix route_xxx deprecations.

### PR DESCRIPTION
**Pull request by dblock**
Will be released as 0.11.0 to support Grape 0.16.x.

### CODE REVIEW

**Comment by dblock** [comment]
@LeFnord Can you look over this and merge? I can cut a 0.11.0 release out of this unless you beat me to it.

**Comment by LeFnord** [comment]
:+1:

**Comment by LeFnord** [comment]
cherry-picked it, cause of merge conflicts … GH is curious since some weeks

**Comment by ShallmentMo** [comment]
I have a problem now. If I use `grape-swagger = 0.20`, the warning come out. If I use `grape-swagger = 0.11.0` , I have to use `grape-entity <  0.5.0`. I'm using `grape-entity =  0.5.1` now. If I change `grape-entity`, I might have to change so much code. Please give me some advice.

**Comment by dblock** [comment]
It sounds like we really want https://github.com/ruby-grape/grape-swagger/issues/314 to be fixed, aka grape-swagger to work with a newer version of grape-entity. I think 0.20 is the way to go, it should probably be locked above grape 0.16.2 and deprecations fixed. Thoughts @LeFnord ?

**Comment by LeFnord** [comment]
yeap, will fix 0.20.0 to grape < 0.15.0 and grape-entity 0.4.8, as in the announcement described :wink: 
see: https://github.com/ruby-grape/grape-swagger/issues/364

**Comment by LeFnord** [comment]
did it: https://github.com/ruby-grape/grape-swagger/pull/383

**Pull request closed without merging**
