### PR TITLE
Added head method type

### PR DESCRIPTION
**Pull request by Bugagazavr**
Grape swagger fails to generate doc if head route exists

### CODE REVIEW

**Comment by dblock** [comment]
This needs tests and a CHANGELOG entry, please.

**Comment by Bugagazavr** [comment]
@dblock ok, when i should place spec?

**Comment by dblock** [comment]
You mean where? I am not sure. You'll have to find a good place, there has been a lot of changes on master I am not too familiar with the updated structure.

**Comment by Bugagazavr** [comment]
done

**Comment by dblock** [comment]
Merged. Is it the same problem for OPTIONS? Want to take care of it?

**Comment by Bugagazavr** [comment]
yep, but this problem can be sovled, by nil check before https://github.com/ruby-grape/grape-swagger/blob/master/lib/grape-swagger/endpoint.rb#L164

**Comment by dblock** [comment]
@Bugagazavr write some specs, make some PRs! Much appreciated.

**Pull request merged**
