### PR TITLE
Deeply nested objects

### PR DESCRIPTION
**Pull request by braktar**
Related to: https://github.com/ruby-grape/grape-swagger/issues/751

### CODE REVIEW

**Comment by braktar** [comment]
A bit of progress on my side. My nested objects have the correct type/format which is encouraging.

**Comment by braktar** [comment]
I've also added a nested object with Array[Array[String]]

**Comment by braktar** [comment]
So, maybe a bit of explanation.

MoveParams was following the formData structure in order to build the definition, losing a lot of information useful for the body format.

So instead of it, the definition is now build with the body format (without losing information) and is then modified only if the formData is required.

**Comment by LeFnord** [comment]
thanks @braktar … good job

**Pull request merged**
