### PR TITLE
#317 - hide version module from path

### PR DESCRIPTION
**Pull request by synth**

### CODE REVIEW

**Comment by dblock** [comment]
Please fix tests, update CHANGELOG and README, squash your commits.

**Comment by synth** [comment]
@dblock tests are failing only on jruby and rbx and from the looks of it were failing before my code as well. any advice? I can take care of changelog, readme, and squashing in the meantime

**Comment by dblock** [comment]
Yeah, ignore the rbx/jruby things, as long as those don't seem to be like new failures. Will look at this separately.

**Comment by synth** [comment]
ugh, i've really fouled the rebasing up. Going to re-fork and try again.

**Pull request closed without merging**
