### PR TITLE
Fix for tags for path versioned endpoints

### LINKED ISSUE #446: Path versioned endpoints gets the version as tag instead of namespace.
When using :path versioned endpoints the endpoints gets tagged by version and not by namespace. That makes Swagger UI group all versioned endpoints under the same group.

### PR DESCRIPTION
**Pull request by anakinj**
This should fix #446

### CODE REVIEW

**Comment by dblock** [comment]
Please check the build and update CHANGELOG.

**Comment by anakinj** [comment]
Updated the Changelog.

The Build failing seemed to have been caused by some kind of connection issue on the runner. Seems to be working now.

**Comment by LeFnord** [comment]
👍 … thanks, for fixing

**Comment by LeFnord** [comment]
@anakinj … can you rebase it …

**Comment by anakinj** [comment]
@LeFnord, this is now rebased

**Comment by LeFnord** [comment]
👍 … thanks

**Pull request merged**
