### PR TITLE
Restore Ruby 3.0 support

### PR DESCRIPTION
**Pull request by godfat**
All tests passed locally. See https://github.com/ruby-grape/grape-swagger/issues/915

### CODE REVIEW

**Comment by LeFnord** [comment]
does it make sense to also readd it to CI matrix, or are you fine with that?

**Comment by LeFnord** [comment]
@godfat ^^^

**Comment by godfat** [comment]
@LeFnord Good question. Thanks for asking. It'll be the best to add it to CI matrix as well. However, I see adding it can increase a lot of cost to CI because there's some combinations of versions. If this is acceptable, that would be great. If it's not, then I think it's fine to support it without actually running CI, especially given that it's not being run for some time and it's still passing?

What do you think?

**Comment by LeFnord** [comment]
mmh … think I'll mörge it, and adapt the CI matrix afterwards, also make a release

**Comment by godfat** [comment]
I amended the commit and added 3.0 support to CI as well. It's very fast. Maybe the cost is fine :)

**Comment by godfat** [comment]
Awesome, thank you so much! A new release will be great, then we can upgrade very quickly.

**Pull request merged**
