### PR TITLE
Fix mounting APIs in route_param namespaces

### PR DESCRIPTION
**Pull request by wojciechka**
This is based on #543  by @milgner and addresses issue #267 

I have applied the changes on top of latest master and included test cases.

### CODE REVIEW

**Comment by LeFnord** [comment]
many thanks for your work @wojciechka … please fix rubocop offences and I'm happyo to mörge it :)

**Comment by LeFnord** [comment]
@wojciechka … please wait, fixing of rubocop stuff is out of scope of this PR

**Comment by wojciechka** [comment]
@LeFnord I have just pushed fixes that clean up offences related to my changes.

As you have probably noticed, most of the issues are not related to the changes in code I have made.

But I also agree that I should not be introducing new offences.

**Comment by LeFnord** [comment]
thanks again @wojciechka … that's what I meant with out of scope ;)
please can you fix the rubocop version to 0.49.1, so all should be fine

**Comment by wojciechka** [comment]
@LeFnord sure, just pushed an update ; also, I am curious, wouldn't `Gemfile.lock` prevent those things from happening (as in an update in rubocop version triggering a lot of false positives)?

I usually commit Gemfile.lock to avoid package versions changing between deployments etc and I saw it explicitly removed.

It's not really related to this PR, but I am curious about it.

**Comment by wojciechka** [comment]
@LeFnord With the rubocop version fix it has passed all the tests now.

Anything pending on my side?

**Comment by LeFnord** [comment]
@wojciechka yhanks again :) … happy to mörge it

**Comment by rypit** [comment]
Also addresses issues similar to #610 & #508 which were happening for me in `0.27.3`. Thanks for this :+1:

**Pull request merged**
