### PR TITLE
Required properties

### PR DESCRIPTION
**Pull request by Bugagazavr**
As mentioned https://github.com/ruby-grape/grape-swagger-entity/issues/34#issuecomment-412338781

Todo:

- [x] Grape swagger entity gem https://github.com/ruby-grape/grape-swagger-entity/pull/35
- [X] Grape swagger representable gem https://github.com/ruby-grape/grape-swagger-representable/pull/11
- [x] This PR

Release:

1. Release **grape-swagger** ( 0.31.0 )
2. Release a new **grape-swagger-entity** ( 0.3.0 ) and **grape-swagger-representable** ( 0.2.0 ), which depends on **grape-swagger** ( 0.31.0 )

### CODE REVIEW

**Comment by LeFnord** [comment]
@Bugagazavr … maybe you have to change your branch name? perhaps travis have some problems with it

**Comment by Bugagazavr** [comment]
@LeFnord it's ok, thats my mistake with selected git upstream ( i'l drop branch from origin, thats why push pipeline failed ).

**Comment by LeFnord** [comment]
ok, fine … 😉

**Comment by Bugagazavr** [comment]
@LeFnord done.

**Comment by LeFnord** [comment]
mmh, a spec as documentation would be nice … 😉

**Comment by LeFnord** [comment]
… think it will be done on the other PRs … so I'll mörge it

**Comment by Bugagazavr** [comment]
@LeFnord yes, i'm working on it, but specs merge is possible after release new parser gems.

**Comment by LeFnord** [comment]
ok, makes sense 😄

**Comment by LeFnord** [comment]
@Bugagazavr … please can you cut a release for grape-swagger-entity, so I can do it here, thanks

**Comment by Bugagazavr** [comment]
@LeFnord yes i can, can you release grape-swagger first?

**Comment by LeFnord** [comment]
mmh … ok, for that the deprecation warning is

sure, I'll do it right now

**Comment by LeFnord** [comment]
@Bugagazavr … 0.31.0 released

**Comment by Bugagazavr** [comment]
@LeFnord  Successfully registered gem: grape-swagger-entity (0.3.0)

**Comment by LeFnord** [comment]
so, with that I can set the minimal required version to 0.3.0 here, right?

**Comment by Bugagazavr** [comment]
@LeFnord yes

**Comment by Bugagazavr** [comment]
Also pushed grape-swagger-representable 0.2.0 to rubygems.org

**Comment by LeFnord** [comment]
so will cut another release 😄

**Pull request merged**
