### PR TITLE
Modify full entity name to be RFC3986 compliant #797

### PR DESCRIPTION
**Pull request by GarrettB71**
Signed-off-by: Garrett Blehm <garrett.blehm@cerner.com>

Addresses issue #797.

Updated `parse_entity_name` method to use RFC3986 compliant `_` instead of `::` as separator.

### CODE REVIEW

**Comment by LeFnord** [comment]
thanks @GarrettB71 … for spotting and fixing it

**Comment by LeFnord** [comment]
mmh a bit strange, travis says it's all fine, but GH ??? … 

please can you push again to trigger the travis pipeline, thanks

**Comment by GarrettB71** [comment]
I believe the build is failing due to a change in `grape-swagger-entity 0.5.0`. It looks like it's trying to `dig` a null value here https://github.com/ruby-grape/grape-swagger-entity/pull/50/files#diff-a5091f3c521e5de0c1dfc6483f237842R16.

**Comment by LeFnord** [comment]
thanks @GarrettB71 

yeap … that was it, it should be fixed now … I'll change onle the Upgrading to the next version, which will be 1.2.0

**Comment by LeFnord** [comment]
please can you adapt this spec [inheritance_and_discriminator_spec.rb#L51-L53](https://github.com/ruby-grape/grape-swagger/blob/master/spec/swagger_v2/inheritance_and_discriminator_spec.rb#L51-L53) … thanks and sorry

**Comment by LeFnord** [comment]
thanks @GarrettB71

**Pull request merged**
