### PR TITLE
Replace downcase with underscore for multi-word roots

### PR DESCRIPTION
**Pull request by bikolya**
It fixes a problem introduced in #761 
When `downcase` was used, `apierror` instead of `api_error` was generated from ApiError entity.

### CODE REVIEW

**Comment by LeFnord** [comment]
thanks … @bikolya, welcome 😄

 and sorry for late replay

**Comment by LeFnord** [comment]
a bit curios … will have a look on it tonight

**Comment by dblock** [comment]
The CHANGELOG complaint is right, you're missing a colon after the PR :)

**Comment by LeFnord** [comment]
ah ok … thanks

**Pull request merged**
