### PR TITLE
use latest ruby version in CI

### PR DESCRIPTION
**Pull request by takkanm**

### CODE REVIEW

**Comment by LeFnord** [comment]
thanks @takkanm … please run `bundle exec rubocop -a` to fix the rubocop offences

**Comment by takkanm** [comment]
@LeFnord Thank you for your response.
This error is due to a change in rubocop default. 

https://github.com/bbatsov/rubocop/pull/4231

Should I fix this error with this pull request? Or should I fix with another pull request?

**Comment by LeFnord** [comment]
@takkanm … yes please fix it with this PR, as I suggested above 😉

**Comment by takkanm** [comment]
Thanks for your advice. I updated this pull request.

**Pull request merged**
