### PR TITLE
Response model can have required attributes

### PR DESCRIPTION
**Pull request by WojciechKo**
Now you can mark attribute that is required in response model.

### CODE REVIEW

**Comment by Bugagazavr** [comment]
Hello, i think that should be a part of https://github.com/ruby-grape/grape-swagger-entity

**Comment by WojciechKo** [comment]
It's not possible because https://github.com/ruby-grape/grape-swagger-entity uses
`GrapeSwagger.model_parsers`.
With that we can manipulate `properties` attribute of model definition but we need to add `required` array to model definition. Like in example:
```
definitions: {
  Location: {
    type: "object",
    properties: {
      id: { type: "integer" },
      name: { type: "string" }
    },
    required: ["id", "name"],
  },
  ...
}
```

**Comment by Bugagazavr** [comment]
Ok thats sounds reasonable, please fix a tests, write a spec for required attributes, put this pull request to `CHAGELOG.md`, and add notes to `README.md` about required attributes

**Comment by WojciechKo** [comment]
Done.

**Comment by LeFnord** [comment]
thanks @WojciechKo … please can you add a section in the README to document it

**Comment by WojciechKo** [comment]
@LeFnord I think that's clear enough :)

**Comment by LeFnord** [comment]
thanks @WojciechKo … it is totally strange … please can you make rubocop happy?

**Comment by LeFnord** [comment]
Why? … hope you want to re-open it

**Pull request closed without merging**
