### PR TITLE
Add response header OpenAPI spec generation

### PR DESCRIPTION
**Pull request by jdmurphy**
Add support to expose [response headers object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headers-object)

* Available only with desc DSL block syntax under success and failure keys.
* Consumer is responsible for documenting headers

### CODE REVIEW

**Comment by LeFnord** [comment]
@jdmurphy thanks for it, but I'm a bit confused, your title says something abvout response example, but your code handles headers …

background: there exists a key `headers` for the describe method, for documenting it  
did your change take the same line?

… and sorry, mörged your second PR rivght now

**Comment by jdmurphy** [comment]
@LeFnord, sorry that was some bad copy/pasting because the feature is similar in scope to @gamartin's addition of response examples.

When I used the `headers` key in the describe block, it showed up as a parameter and not in the response area. It is possible I was not using it correctly/there was something I missed when I added it; if so please let me know.

**Comment by LeFnord** [comment]
@jdmurphy … yeap, you are right, `success` and `failures` will be used for documenting the response and the `headers` key as kind as parameter for the request

**Comment by LeFnord** [comment]
thanks for your contributions @jdmurphy

**Pull request merged**
